In [1]:
import numpy as np
import pandas as pd


In [3]:
df=pd.read_csv('Churn_Modelling.csv')

In [4]:
df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [5]:
df.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [7]:
df.duplicated().sum()

0

In [8]:
X=df.iloc[:,3:].values
Y=df.iloc[:,13:14].values


**CLASSIFICATION USING ANN**

In [9]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.pipeline import Pipeline

In [10]:
ct = ColumnTransformer([('oh',OneHotEncoder(),[1,2])],remainder='passthrough')
X=ct.fit_transform(X)

In [11]:
X

array([[1.0, 0.0, 0.0, ..., 1, 101348.88, 1],
       [0.0, 0.0, 1.0, ..., 1, 112542.58, 0],
       [1.0, 0.0, 0.0, ..., 0, 113931.57, 1],
       ...,
       [1.0, 0.0, 0.0, ..., 1, 42085.58, 1],
       [0.0, 1.0, 0.0, ..., 0, 92888.52, 1],
       [1.0, 0.0, 0.0, ..., 0, 38190.78, 0]], dtype=object)

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.25,random_state=42)

In [15]:
a = np.arange(9).reshape(3,3)

In [16]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [17]:
from sklearn.preprocessing import StandardScaler

In [18]:
sc= StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

Steps:
1) add input layer : number of inut neurons,weight stratergy, activation func

2) hidden layer  : same as input layer
3)  output layer : same as input but activation func is 'relu' for regression
binary : 'threshold/sigmoid'
categorical : 'softmax'

**IMPORT DL LIBRARIES**

In [19]:
from tensorflow.keras.models import Sequential
from keras.layers import Dense

We initialise model with Sequential/API
ANN is a feed forward network (as it has input layer,hidden layer,output layer) so we need to use Sequential type of initialising

In [21]:
X.shape

(10000, 14)

In [20]:
model = Sequential()

In [23]:
model.add(Dense(units=13,activation='relu',kernel_initializer='random_uniform'))

Hidden Layer

In [24]:
model.add(Dense(units=13*2,activation='relu',kernel_initializer='random_uniform'))

In [25]:
model.add(Dense(units=26,activation='relu',kernel_initializer='random_uniform'))

In [26]:
model.add(Dense(units=13*2,activation='relu',kernel_initializer='random_uniform'))

Output Layer

In [28]:
model.add(Dense(units=1,activation='sigmoid',kernel_initializer='random_uniform'))

Compile model

In [32]:
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [33]:
model.fit(X_train,Y_train,batch_size=32,epochs=25)

Epoch 1/25
235/235 [==============================] - 3s 2ms/step - loss: 0.3859 - accuracy: 0.7947
Epoch 2/25
235/235 [==============================] - 0s 2ms/step - loss: 0.1404 - accuracy: 0.9256
Epoch 3/25
235/235 [==============================] - 0s 2ms/step - loss: 0.1249 - accuracy: 1.0000
Epoch 4/25
235/235 [==============================] - 0s 2ms/step - loss: 0.1102 - accuracy: 1.0000
Epoch 5/25
235/235 [==============================] - 0s 2ms/step - loss: 0.0969 - accuracy: 1.0000
Epoch 6/25
235/235 [==============================] - 0s 2ms/step - loss: 0.0850 - accuracy: 1.0000
Epoch 7/25
235/235 [==============================] - 0s 2ms/step - loss: 0.0747 - accuracy: 1.0000
Epoch 8/25
235/235 [==============================] - 0s 2ms/step - loss: 0.0656 - accuracy: 1.0000
Epoch 9/25
235/235 [==============================] - 0s 2ms/step - loss: 0.0578 - accuracy: 1.0000
Epoch 10/25
235/235 [==============================] - 0s 2ms/step - loss: 0.0509 - accuracy: 1.0000

In [34]:
ypred = model.predict(X_test)

79/79 [==============================] - 0s 2ms/step


In [35]:
ypred

array([[2.0044367e-07],
       [2.0734888e-08],
       [1.3206186e-07],
       ...,
       [6.8561321e-09],
       [2.5594304e-08],
       [1.9139911e-08]], dtype=float32)

In [36]:
ypred = ypred>0.5

In [37]:
ypred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [39]:
Y_test

array([[0],
       [0],
       [0],
       ...,
       [0],
       [0],
       [0]])

In [40]:
df.head(1)

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   

   Tenure  Balance  NumOfProducts  HasCrCard  IsActiveMember  EstimatedSalary  \
0       2      0.0              1          1               1        101348.88   

   Exited  
0       1

In [42]:
yp=model.predict()

ValueError: ignored