In [2]:
import tensorflow as tf
print("the version of tensorflow I use here is: ", tf.__version__)

the version of tensorflow I use here is:  2.14.0


In [3]:
mnist = tf.keras.datasets.mnist

In [4]:
(x_train,y_train), (x_test,y_test) = mnist.load_data()
x_train, x_test = x_train/255.0, x_test/255.0

11490434/11490434 [==============================] - 0s 0us/step


In [5]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [6]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.4829082 ,  0.18610129, -0.38242856,  0.9691548 ,  0.3193532 ,
        -0.22171843,  0.16276509, -0.3652619 ,  0.16414505,  0.49014154]],
      dtype=float32)

In [7]:
tf.nn.softmax(predictions).numpy()

array([[0.05142182, 0.10039094, 0.05685716, 0.2196698 , 0.11470045,
        0.06676991, 0.09807533, 0.05784164, 0.09821077, 0.13606222]],
      dtype=float32)

In [8]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [9]:
loss_fn(y_train[:1], predictions).numpy()

2.706503

In [10]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [11]:
model.fit(x_train, y_train, epochs=12)

Epoch 1/12
1875/1875 [==============================] - 5s 2ms/step - loss: 0.3013 - accuracy: 0.9125
Epoch 2/12
1875/1875 [==============================] - 5s 3ms/step - loss: 0.1464 - accuracy: 0.9564
Epoch 3/12
1875/1875 [==============================] - 5s 3ms/step - loss: 0.1079 - accuracy: 0.9671
Epoch 4/12
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0873 - accuracy: 0.9734
Epoch 5/12
1875/1875 [==============================] - 5s 3ms/step - loss: 0.0754 - accuracy: 0.9765
Epoch 6/12
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0641 - accuracy: 0.9803
Epoch 7/12
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0580 - accuracy: 0.9814
Epoch 8/12
1875/1875 [==============================] - 5s 3ms/step - loss: 0.0515 - accuracy: 0.9830
Epoch 9/12
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0480 - accuracy: 0.9841
Epoch 10/12
1875/1875 [==============================] - 4s 2ms/step - loss: 0.044

In [12]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 1s - loss: 0.0770 - accuracy: 0.9798 - 756ms/epoch - 2ms/step


[0.07701977342367172, 0.9797999858856201]

In [13]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [14]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[8.6470961e-12, 9.4093500e-12, 9.0840541e-07, 3.2233179e-06,
        1.5071138e-17, 1.4657996e-09, 1.7017990e-19, 9.9999547e-01,
        1.4649513e-11, 3.3916933e-07],
       [1.1942204e-13, 1.3470458e-06, 9.9999857e-01, 2.0639449e-08,
        1.3499159e-25, 1.1156702e-08, 6.5778823e-12, 8.7735951e-17,
        1.8898296e-11, 3.2998406e-20],
       [1.8703714e-09, 9.9981791e-01, 7.5417609e-07, 2.3571013e-07,
        1.6970142e-06, 4.4520775e-08, 8.6403571e-07, 1.7086776e-04,
        7.6147871e-06, 8.5484206e-09],
       [9.9997652e-01, 2.1170101e-12, 8.4762914e-06, 3.4153927e-10,
        2.5685723e-13, 1.4467645e-06, 9.0366523e-09, 3.7374616e-07,
        2.3839816e-11, 1.3237324e-05],
       [9.0425791e-09, 4.8783481e-16, 4.9186442e-09, 5.7317513e-13,
        9.9856937e-01, 2.7411545e-16, 2.1321951e-10, 2.2352579e-07,
        1.9151117e-10, 1.4304029e-03]], dtype=float32)>